version: "3.7"
services:
    atlassian-confluence:
        container_name: atlassianConfluenceDev

        environment:
            FORCE_COLOR: 1
            ATL_JDBC_URL: jdbc:postgresql://postgres:5432/${PG_DB-atlassianConfluenceDev}
            ATL_JDBC_USER: ${PG_USER-atlassianConfluenceDev}
            ATL_JDBC_PASSWORD: ${PG_PASSWORD-966VHT7SUcPnaqpJAz32fP}
            ATL_DB_TYPE: postgresql

        ports:
            - ${PORT-8098}:8090

    postgres:
        ports:
            - 5432

        container_name: atlassianConfluencePostgresqlDev

        environment:
            FORCE_COLOR: 1
            POSTGRES_USER: ${PG_USER-atlassianConfluenceDev}
            POSTGRES_PASSWORD: ${PG_PASSWORD-966VHT7SUcPnaqpJAz32fP}
            POSTGRES_DB: {PG_DB-atlassianConfluenceDev}
